application:
  booking:
    kafka:
      store-name: booking-events-store

spring:
  application:
    name: booking-service

  cloud:
    stream:
      bindings:
        bookingEventSupplier-out-0:
          destination: booking-events
          contentType: application/avro
          producer:
            batch:
              size: 16384
            linger:
              ms: 90
            acks: 1

        processBookingEvents-in-0:
          destination: booking-events
          contentType: application/avro

      schemaRegistryClient:
        endpoint: http://localhost:8990

      schema:
        avro:
          dynamicSchemaGenerationEnabled: true

    kafka:
      streams:
        binder:
          stateStoreRetry:
            maxAttempts: 5
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

  grpc:
    server:
      address: 0.0.0.0
      port: 9090
