application:
  booking:
    kafka:
      store-name: booking-events-store

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    streams:
      bootstrap-servers: 127.0.0.1:9092
      application-id: booking-service
    consumer:
      group-id: hotel-pms-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.cloudevents.kafka.CloudEventSerializer

grpc:
  server:
    address: 0.0.0.0
    port: 9090