application:
  booking:
    kafka:
      store-name: booking-events-store

spring:
  application:
    name: booking-service

  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    stream:
      bindings:
        bookingEventSupplier-out-0:
          destination: booking-events
          contentType: application/json
          producer:
            batch:
              size: 16384
            linger:
              ms: 90
            acks: 1

        processBookingEvents-in-0:
          destination: booking-events
          contentType: application/json

    kafka:
      streams:
        binder:
          stateStoreRetry:
            maxAttempts: 5

  grpc:
    server:
      address: 0.0.0.0
      port: 9090
