application:
  booking:
    kafka:
      store-name: booking-events-store

spring:
  application:
    name: booking-service

  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    stream:
      bindings:
        bookingEventSupplier-out-0:
          destination: booking-events
          contentType: application/avro
          producer:
            batch:
              size: 16384
            linger:
              ms: 90
            acks: 1
            configuration:
              schema.registry.url: http://localhost:8990
              value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

        processBookingEvents-in-0:
          destination: booking-events
          contentType: application/avro
          consumer:
            configuration:
              schema.registry.url: http://localhost:8990
              value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer



    kafka:
      streams:
        binder:
          stateStoreRetry:
            maxAttempts: 5
          configuration:
            schema.registry.url: http://localhost:8990
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  grpc:
    server:
      address: 0.0.0.0
      port: 9090
