application:
  booking:
    kafka:
      store-name: booking-events-store

spring:
  application:
    name: booking-service
  cloud:
    stream:
      bindings:
        bookingEventSupplier-out-0:
          destination: booking-events
          contentType: application/json
        processBookingEvents-in-0:
          destination: booking-events
          contentType: application/json
    kafka:
      streams:
        binder:
          stateStoreRetry:
            maxAttempts: 5
          configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

grpc:
  server:
    address: 0.0.0.0
    port: 9090