name: CD - Release & Publish OCI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Docker (for OCI image publishing)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set project version from date
        id: tagger
        run: |
          VERSION=$(date +'%Y.%m.%d.%H%M%S')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set version in gradle.properties
        run: |
          echo "version=${{ steps.tagger.outputs.version }}" > gradle.properties

      - name: Build & Publish OCI Image using bootBuildImage
        run: ./gradlew bootBuildImage --no-daemon

      - name: Generate Release Notes
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            LOG=$(git log "$LAST_TAG"..HEAD --pretty=format:"- %s")
          else
            LOG=$(git log --pretty=format:"- %s")
          fi
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "v${{ steps.tagger.outputs.version }}"
          git push origin "v${{ steps.tagger.outputs.version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.tagger.outputs.version }}
          name: Release v${{ steps.tagger.outputs.version }}
          body: ${{ steps.changelog.outputs.log }}
