name: CD - Release & Publish Docker

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate version tag
        id: tagger
        run: |
          TAG="v$(date +'%Y.%m.%d.%H%M%S')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag "$TAG"
          git push origin "$TAG"

      - name: Generate Release Notes
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            LOG=$(git log "$LAST_TAG"..HEAD --pretty=format:"- %s")
          else
            LOG=$(git log --pretty=format:"- %s")
          fi
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tagger.outputs.tag }}
          name: Release ${{ steps.tagger.outputs.tag }}
          body: ${{ steps.changelog.outputs.log }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/j4c62/pms-booking-service:${{ steps.tagger.outputs.tag }} \
            -f .docker/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/j4c62/pms-booking-service:${{ steps.tagger.outputs.tag }}
