name: CD - Release & Publish Docker

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate version tag
        id: tagger
        run: |
          TAG="v$(date +'%Y.%m.%d.%H%M%S')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag "$TAG"
          git push origin "$TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagger.outputs.tag }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/pms-booking-service:${{ steps.tagger.outputs.tag }} .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/pms-booking-service:${{ steps.tagger.outputs.tag }}
