name: CI - Build & CodeQL

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  codeql-analysis:
    uses: github/codeql-action/analyze@v3
    permissions:
      security-events: write
